name: Generate Vortex Version
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
    - name: Wait for tag addition and generate Vortex version
      id: version
      run: |
        echo "Waiting for a tag to be added..."
        MAX_RETRIES=10
        RETRY_COUNT=0
        RETRY_INTERVAL=10
        TAG=""
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          # Check if there's a tag
          TAG=$(git describe --tags --abbrev=0 || true)
          if [ -n "$TAG" ]; then
            echo "Found tag: $TAG"
            break
          else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            echo "No tags found, retrying... ($RETRY_COUNT/$MAX_RETRIES)"
            sleep $RETRY_INTERVAL
          fi
        done
        if [ -z "$TAG" ]; then
          echo "No tags found after $MAX_RETRIES retries. Exiting."
          exit 1
        fi
        TIMESTAMP=$(date +%s%N)
        CORE=$(echo $TAG | cut -d '.' -f 1 | sed 's/v//')
        FLOW=$(echo $TAG | cut -d '.' -f 2)
        PATCH=$(echo $TAG | cut -d '.' -f 3)
        CUSTOM_TAGS=""
        if [[ $(git tag -l "beta*") ]]; then
          CUSTOM_TAGS="${CUSTOM_TAGS}_beta"
        fi
        if [[ $(git tag -l "hotfix*") ]]; then
          CUSTOM_TAGS="${CUSTOM_TAGS}_hotfix"
        fi
        VERSION="Vortex-${CORE}.${FLOW}.${PATCH}_${TIMESTAMP}${CUSTOM_TAGS}"
        echo "---------------------"
        echo "[Release: Vortex]"
        echo "[Core: $CORE, Flow: $FLOW, Patch: $PATCH]"
        echo "[Version: $VERSION]"
        echo "---------------------"
        echo "::set-output name=version::$VERSION"
    - name: Catch up with newer commits and create new versions
      run: |
        LATEST_TAG=$(git describe --tags --abbrev=0)
        echo "Latest tag: $LATEST_TAG"
        TAG_HASH=$(git rev-list -n 1 $LATEST_TAG)
        echo "Latest tag hash: $TAG_HASH"
        COMMITS=$(git log $TAG_HASH..HEAD --oneline)
        
        if [ -z "$COMMITS" ]; then
          echo "No new commits found since the last tag."
        else
          echo "New commits since the last tag:"
          echo "$COMMITS"
        fi
        NEW_VERSION="Vortex-${CORE}.${FLOW}.$((PATCH+1))_${TIMESTAMP}_release"
        echo "Creating new release version: $NEW_VERSION"
        git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"
        echo "Pushing the new version tag to GitHub..."
        git push origin "$NEW_VERSION"
        echo "::set-output name=new_version::$NEW_VERSION"
        echo "New version tag pushed: $NEW_VERSION"
